netlify.toml, package.json, src/App.jsx, src/utils/api.js
- Set-up infrastructure / DevOps
- API responses in deploy-preview and the `develop`-branch
=> Adding API URLs dependent on stage of the branch in the pipeline

.eslintrc.js, package.json, src/components/organisms/__tests__/__snapshots__/Footer.test.js.snap, src/components/styles/views/PageNotFoundStyling.js, src/components/views/PageNotFound.jsx
- Code Quality on PageNotFound.js
- All Style components have been moved from the file and places within `./styles/views/PageNotFoundStyling.js`. Imported into original file and styling imports refactored. This has been checked against live server
https://trello.com/c/3gZc8fZE/151-front-end-code-quality-control-views-components
Official testing is currently under review. Styling has been confirmed working via the live server.
=> Style components removed and imported from a new styling file

src/hooks/events.js
- Ensuring code quality - Hooks have been reviewed for quality and refactor
- 2 hooks removed as they are irrelevant and not required.
- File is now significantly smaller and therefore breaking it down into further files is not required. 
https://trello.com/c/A69NG7R8/152-front-end-code-quality-control-hooks
- No tests currently exist for these components.
- All current tests running and passing fine.
- Ensure compoents render correctly.
- This has also been checked throughout the works completed
- [ N/A ] I have commented my code, particularly in hard-to-understand areas
- [ N/A ] I have made corresponding changes to the documentation
- Question #1:
- Question #2:
=> Removed irrelevant hooks

src/components/organisms/__tests__/Header.test.js, src/components/organisms/__tests__/__snapshots__/Header.test.js.snap, src/components/templates/__tests__/__snapshots__/EventOnboarding.test.js.snap, src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap
All the tests on Header.js are passing,and the test rate coverage is 100%
Task Description:Writing unit tests for Header.js
Trello Card Link: https://trello.com/c/3KGB8qjo/199-front-endtest-organisms-headerjs
- Unit test
- Tests are passing
=> Tests on Header 🧪 

src/components/views/__tests__/PageNotFound.test.js, src/components/views/__tests__/__snapshots__/PageNotFound.test.js.snap
Task Description:Writing tests for PageNotFound.js
Trello Card Link: https://trello.com/c/4iZDxzxu/211-front-endtest-view-pagenotfoundjsx
- Unit tests
- Tests all passing
- Code is clean
=> Testing/pageNotFound 🧪 

src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap, src/store/user/__tests__/actions.test.js, src/store/user/actions.js
Task Description:Writing tests for every function for store/user/actions.js
Trello Card Link: https://trello.com/c/rujkbH57/219-front-endtests-store-user
- Test for every function on the file.
- All functions have been tested
- All tests are passing
=> Testing/store/user 🧪 

src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap, src/store/events/__tests__/actions.test.js
Task Description: 
To make sure that all components keep functioning adequately without breaking the overall application (i.e. when a dev applies some new changes and inadvertently break other functionality through side-effects), moreover to be able to quickly identify bugs as they arise.
Adding good unit and integration tests ensure that store/redux works as intended and will help debug future feature expansion.
Trello Card Link: https://trello.com/c/JB1xJzIz/214-front-endtests-store-events
- Unit tests for all the action creators.
- All the functions in the file are being tested.
- The tests pass with a 100% coverage rate.
=> Testing/store/events 🧪 

src/store/projectSubmission/__tests__/actions.test.js, src/utils/mockData.js
Task Description: 
To make sure that all components keep functioning adequately without breaking the overall application (i.e. when a dev applies some new changes and inadvertently break other functionality through side-effects), moreover to be able to quickly identify bugs as they arise.
Adding good unit and integration tests ensure that store/redux works as intended and will help debug future feature expansion.
Trello Card Link: https://trello.com/c/38eSQEk8/218-front-endtests-store-projectsubmission
- Unit tests for all the action creators.
- All the functions in the file are being tested.
- The tests pass with a 100% coverage rate.
=> Testing/store/projectSubmission 🧪 

src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap, src/store/participantTeams/__tests__/actions.test.js, src/utils/mockData.js
Task Description: 
To make sure that all components keep functioning adequately without breaking the overall application (i.e. when a dev applies some new changes and inadvertently break other functionality through side-effects), moreover to be able to quickly identify bugs as they arise.
Adding good unit and integration tests ensure that store/redux works as intended and will help debug future feature expansion.
Trello Card Link: https://trello.com/c/v5UIKSMA/216-front-endtests-store-participantteams
- Unit tests for all the action creators.
- All the functions in the file are being tested.
- The tests pass with a 100% coverage rate.
=> Testing/store/participantTeams 🧪 

src/components/templates/HackathonProjects.js, src/components/templates/__tests__/HackathonProjects.test.js, src/components/templates/__tests__/TeamView.test.js, src/components/templates/__tests__/__snapshots__/TeamView.test.js.snap
- Adding tests to TeamView.js
- 5 tests implemented 
- 76.92% coverage - remaining coverage not hit due to conditionals with custom hook requirements.
- Amend typos in previous files
https://trello.com/c/7V1c3Z5V/190-front-endtest-template-teamviewjs
- toMatchSnapshot()
- 3 x queryByText().toBeInTheCodument() 
- (querySelector().getAttribute()).toBe()
- Check all tests are running - screenshot provided
=> Add 5 tests to TeamView

src/components/templates/UserProfile.jsx, src/components/templates/__tests__/UserProfile.test.js, src/components/templates/__tests__/__snapshots__/UserProfile.test.js.snap
- Adding tests
Adding good unit and integration tests ensure that `UserProfile.js` works as intended and will help debug future feature expansion.
Trello Card Link: https://trello.com/c/JWHoi3uW/192-front-endtest-template-userprofilejsx
- Unit testing
- Test coverage is at least 70%.
=> Testing/user profile 🧪 

src/components/templates/__tests__/TeamView.test.js, src/components/views/__tests__/LoginPage.test.js, src/components/views/__tests__/__snapshots__/LoginPage.test.js.snap
- Adding tests on LoginPage.js
- 4 tests implemented 
- 100% coverage
https://trello.com/c/d2coTr3w/207-front-endtest-view-loginjsx
- .toMatchSnapShot()
- 3x .queryByText().toBeInDocument()
- Check tests are passing - screenshots provided below
- Question #1:
- Question #2:
=> Add 4 tests to LoginPage

src/components/views/__tests__/SignupPage.test.js, src/components/views/__tests__/__snapshots__/SignupPage.test.js.snap
- Adding tests
Adding good unit and integration tests ensure that `SignupPage.js` works as intended and will help debug future feature expansion.
Trello Card Link: https://trello.com/c/acHUbsDS/215-front-endtest-view-signuppagejsx
- Unit testing
- Test coverage is at least 70%.
=> Testing/SignupPage 🧪 

package.json, src/components/templates/__tests__/ParticipantSubmission.test.js, src/utils/mockData.js
Trello Card Link: https://trello.com/c/xuQdkgSM
- Test #1 : Added tests to check the Submit is in the document. 
- Test Rubs
- Question #1:
- Question #2:
=> Tests participant submission

src/components/templates/__tests__/__snapshots__/HackathonSingleProject.test.js.snap, src/components/views/__tests__/ParticipantSubmissionPage.test.js, src/components/views/__tests__/__snapshots__/ParticipantSubmissionPage.test.js.snap, src/utils/mockData.js
- Adding tests
Adding good unit and integration tests ensure that `ParticipantSubmissionPagejs` works as intended and will help debug future feature expansion.
Trello Card Link: https://trello.com/c/4hS9MK5g/209-front-endtest-view-participatsubmissionpagejsx
- Unit testing
=> Testing/ParticipantsubmissionPage 🧪 

src/components/templates/__tests__/__snapshots__/HackathonSingleProject.test.js.snap, src/components/views/__tests__/HackathonProjectPage.test.js, src/components/views/__tests__/__snapshots__/HackathonProjectPage.test.js.snap
- Adding tests
Adding good unit and integration tests ensure that `HackathonProjectPage` works as intended and will help debug future feature expansion.
Trello Card Link: https://trello.com/c/RT32HbSE/212-front-endtests-views-hackathonprojectpagejsx
- Unit testing
=> Testing/HackathonProjectPage 🧪 

src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap, src/components/views/__tests__/HackathonSinglePage.test.js, src/components/views/__tests__/__snapshots__/HackathonSinglePage.test.js.snap, src/components/views/__tests__/__snapshots__/ParticipantSubmissionPage.test.js.snap
Adding good unit and integration tests ensure that `HackathonSinglePage` works as intended and will help debug future feature expansion.
Trello Card Link: https://trello.com/c/lWDEXV6D/217-front-endtests-views-hackathonsinglepagejsx
- Unit testing
=> HackathonSinglePage 🧪 

src/components/views/__tests__/HackathonProjectsPage.test.js, src/components/views/__tests__/__snapshots__/HackathonProjectsPage.test.js.snap
Adding good unit and integration tests ensure that `HackathonProjectsPage` works as intended and will help debug future feature expansion.
Trello Card Link: https://trello.com/c/qTQtergU/213-front-endtests-views-hackathonprojectspagejsx
- Unit testing
=> Testing/HackathonProjectsPage 🧪 

src/components/templates/__tests__/__snapshots__/AddParticipantTeams.test.js.snap, src/components/templates/__tests__/__snapshots__/AddTeammates.test.js.snap, src/components/templates/__tests__/__snapshots__/EventOnboarding.test.js.snap, src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap, src/components/templates/__tests__/__snapshots__/HackathonProjects.test.js.snap, src/components/templates/__tests__/__snapshots__/HackathonSingle.test.js.snap, src/components/templates/__tests__/__snapshots__/HackathonSingleProject.test.js.snap, src/components/templates/__tests__/__snapshots__/UserProfile.test.js.snap, src/components/views/__tests__/HackathonFormPage.test.js, src/components/views/__tests__/__snapshots__/HackathonFormPage.test.js.snap, src/components/views/__tests__/__snapshots__/HackathonProjectPage.test.js.snap, src/components/views/__tests__/__snapshots__/HackathonProjectsPage.test.js.snap, src/components/views/__tests__/__snapshots__/HackathonSinglePage.test.js.snap, src/components/views/__tests__/__snapshots__/ParticipantSubmissionPage.test.js.snap, src/utils/mockData.js
Adding good unit and integration tests ensure that `HackathonFormPage` works as intended and will help debug future feature expansion.
Trello Card Link: https://trello.com/c/8JF0bgmg/208-front-endtests-views-hackathonformpagejsx#
- Unit testing
=> Testing/HackathonFormPage 🧪 

src/components/templates/__tests__/UserProfileForm.test.js, src/components/templates/__tests__/__snapshots__/UserProfileForm.test.js.snap
Trello Card Link: https://trello.com/c/duNOM8qN
- Test #1 : Test to check if the page renders.
- Test #2 : Check if the text node for the heading displays text.
- Test #3
- If test passes.
- Question #1:
- Question #2:
=> Testing userprofileform

src/components/templates/__tests__/UserProfileForm.test.js, src/components/templates/__tests__/__snapshots__/UserProfileForm.test.js.snap
Trello Card Link: https://trello.com/c/duNOM8qN
- Test #1 : Added a snapshot test. 
- Mobile responsiveness
- Data validation
- Ex. #3
- Question #1:
- Question #2:
=> added the tests for the userprofileform

src/components/views/__tests__/UserProfileFormPage.test.js, src/components/views/__tests__/__snapshots__/UserProfileFormPage.test.js.snap, src/utils/mockData.js
Adding good unit and integration tests ensure that `UserProfileFormPage` works as intended and will help debug future feature expansion.
Trello Card Link: https://trello.com/c/6hsCSuFK/220-front-endtest-view-userprofileformpagejsx
- Unit testing
=> Testing/UserProfileFormPage 🧪 

src/components/templates/__tests__/CreateTeam.test.js, src/components/templates/__tests__/__snapshots__/CreateTeam.test.js.snap
Adding good unit and integration tests ensure that `CreateTeam.js` works as intended and will help debug future feature expansion.
Trello Card Link: https://trello.com/c/HNxMaY6U/184-front-endtest-template-createteamjsx
- Unit testing
=> Testing/CreateTeam.js 🧪 

src/__test__/App.test.js, src/__test__/__snapshots__/App.test.js.snap
Adding good unit and integration tests ensure that `App.js` and `PrivateRoute.js` works as intended and will help debug future feature expansion.
Trello Card Link: https://trello.com/c/fI8ry4Rm/203-front-endtest-organisms-privateroutejsx
- Unit testing
=> Testing/App_PrivateRoute 🧪 

src/components/templates/UserProfileForm.jsx, src/components/templates/__tests__/UserProfileForm.test.js, src/components/views/__tests__/UserProfilePage.test.js, src/components/views/__tests__/__snapshots__/UserProfilePage.test.js.snap, src/utils/mockData.js
- Adding tests 
Trello Card Link: https://trello.com/c/rIWDpdHi 
- Test #1  - Certifying the snapshot runs.
- Mobile responsiveness
- Data validation
- Ex. #3
- Question #1:
- Question #2:
=> created a test for userprofilepage

src/components/views/__tests__/Dashboard.test.js
- Adding tests for the Dashboard view.
Adding good unit and integration tests ensure that `Dashboard.js` works as intended and will help debug future feature expansion.
- `/view` folder and all components should have adequate unit tests (See `Checklist`)
Trello Card Link: https://trello.com/c/oNqxgehy/158-front-endtests-views-dashboardjsx
- Unit testing
=> Testing/views/Dashboard 🧪

src/__test__/__snapshots__/App.test.js.snap, src/components/molecules/__tests__/__snapshots__/MediaIcons.test.js.snap, src/components/molecules/__tests__/__snapshots__/SocialMedia.test.js.snap, src/components/templates/__tests__/EditHackathon.test.js, src/components/templates/__tests__/__snapshots__/EditHackathon.test.js.snap, src/components/templates/__tests__/__snapshots__/EventOnboarding.test.js.snap, src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap, src/components/templates/__tests__/__snapshots__/UserProfile.test.js.snap, src/components/views/__tests__/__snapshots__/Dashboard.test.js.snap, src/components/views/__tests__/__snapshots__/HackathonFormPage.test.js.snap, src/components/views/__tests__/__snapshots__/PageNotFound.test.js.snap
Adding good unit and integration tests ensure that `EditHackathon.js` works as intended and will help debug future feature expansion.
Trello Card Link: https://trello.com/c/8GUdlr7G/259-testing-edithackathon
- UI tests
- All tests are passing.
=> Testing/EditHackathon 🧪 

src/components/templates/__tests__/Widgets.test.js, src/components/templates/__tests__/__snapshots__/Widgets.test.js.snap, src/components/templates/widgets.js, src/utils/mockData.js
- Adding tests 
Trello Card Link:  https://trello.com/c/DXZI0ILQ
- Added a UI test on the participantinvitewidget.
- If test runs.
- Nil
=> Testing widgets

src/components/molecules/__tests__/__snapshots__/MediaIcons.test.js.snap, src/components/molecules/__tests__/__snapshots__/SocialMedia.test.js.snap, src/components/views/resetPassword/__tests__/ResetPassword.test.js, src/components/views/resetPassword/__tests__/__snapshots__/ResetPassword.test.js.snap
Adding good unit and integration tests ensure that `ResetPassword.js` works as intended and will help debug future feature expansion.
Trello Card Link: https://trello.com/c/5fSoTQER/261-testing-resetpasswordjs
- UI tests
- All tests are passing.
=> Testing/resetPassword 🧪 

src/components/views/resetPassword/__tests__/ResetPasswordConfirmation.test.js, src/components/views/resetPassword/__tests__/__snapshots__/ResetPasswordConfirmation.test.js.snap
Adding good unit and integration tests ensure that `ResetPasswordConfirmation.js` works as intended and will help debug future feature expansion.
Trello Card Link: https://trello.com/c/ZBsUPY9n/262-testing-resetpasswordconfirmation
- UI tests
- All tests are passing.
=> Testing/resetPasswordConfirmation 🧪 

src/components/views/resetPassword/__tests__/NewPassword.test.js, src/components/views/resetPassword/__tests__/__snapshots__/NewPassword.test.js.snap
Adding good unit and integration tests ensure that `NewPassword` works as intended and will help debug future feature expansion.
Trello Card Link: https://trello.com/c/EJPmU3RP/263-testing-newpasswordjs
- UI tests
- All tests are passing.
=> Testing/NewPassword 🧪 

src/components/molecules/__tests__/__snapshots__/MediaIcons.test.js.snap, src/components/molecules/__tests__/__snapshots__/SocialMedia.test.js.snap, src/components/templates/__tests__/__snapshots__/EditHackathon.test.js.snap, src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap, src/components/views/__tests__/__snapshots__/HackathonFormPage.test.js.snap, src/utils/mockData.js
- Bug fixish????
- Test #1
- Test #2
- Test #3
- Mobile responsiveness
- Data validation
- Ex. #3
- Question #1:
- Question #2:
=> Amend mock data dates to use moment

src/components/templates/__tests__/HackathonForm.test.js, src/utils/mockData.js
- Bug fix??
- Test #1
- Test #2
- Test #3
- Mobile responsiveness
- Data validation
- Ex. #3
- Question #1:
- Question #2:
=> Update HackathonFrom.test with state
